name: "CI: PR Validation"

on:
  pull_request:
    branches: [develop, "release/**", main]

jobs:
  prepare:
    uses: ./.github/workflows/_prepare.yml

  build-test:
    needs: [prepare]
    uses: ./.github/workflows/_build-test.yml

  sast:
    needs: [build-test]
    uses: ./.github/workflows/_sast-analysis.yml

  qa:
    needs: [build-test]
    uses: ./.github/workflows/_qa-analysis.yml
